### ISSUE TITLE
🦠 Model Request: Predict bioactivity against Main Protease of SARS-CoV-2

### ISSUE THREAD

**Issue by HarmonySosa** [ersilia-os/ersilia#1180]
### Model Name

Predict bioactivity against Main Protease of SARS-CoV-2

### Model Description

MProPred predicts the efficacy of compounds against the main protease of SARS-CoV-2, which is a promising drug target since it processes polyproteins of SARS-CoV-2. This model uses PaDEL-Descriptor to calculate molecular descriptors of compounds. It is based on a dataset of 758 compounds that have inhibition efficacy against the Main Protease, as published in peer-reviewed journals between January, 2020 and August, 2021. Input compounds are compared to compounds in the dataset to measure molecular similarity with MACCS.

### Slug

bioactivity-against-main-protease-prediction

### Tag

Sars-CoV-2

### Publication

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10289339/

### Source Code

https://github.com/Nadimfrds/Mpropred

### License

MIT

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

Good start, a couple comments before we approve the request:
I think the tags will not work as they are not from the approved list (in GitBook) - they are python-based so strings need to match
Slugs also have a word limit, something like mpro-covid19 would be better

Can you modify those fields before we approve the model?

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa !

This model is using PADEL Descriptors to calculate MACCS Fingerprints. In our experience, the PADEL package is not very well integrated with Python and can bring problems.
Can you try to see if the MACCS fingerprints we obtain with RDKIT (MACCS Keys) are the same as the ones we obtain with the MPro Predictor.

It should be something like.. (making the function up, look for the right one)

```
from rdkit.Chem import MACCSKeys
maccskeys = [MACCSKeys(smi) for smi in smiles_list]
```

This will allow us to modify the calculate descriptors function:
```
# Molecular descriptor calculator option
    def desc_calc():
        # Performs the descriptor calculation
        bashCommand = "java -Xms2G -Xmx2G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/MACCSFingerprinter.xml -dir ./ -file descriptors_output.csv"
        process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        os.remove('molecule.smi')
```

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron! 

Here are the desc_calc and build_model functions using PADEL:

    def desc_calc():
        # Performs the descriptor calculation
        bashCommand = "java -Xms2G -Xmx2G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/MACCSFingerprinter.xml -dir ./ -file descriptors_output.csv"
        process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        os.remove('molecule.smi')

    def build_model(input_data):
        # Reads in saved regression model
        load_model = pickle.load(open('Mpro_model.pkl', 'rb')) #  06.25.24 broken up to handle dtype error
        # Apply model to make predictions
        prediction = load_model.predict(input_data)
        st.header('**Prediction results**')
        prediction_output = pd.Series(prediction, name='pIC50')
        molecule_name = pd.Series(load_data[1], name='molecule_name')
        df = pd.concat([molecule_name, prediction_output], axis=1)
        st.write(df)
        st.markdown(filedownload(df), unsafe_allow_html=True)

These are the results I get when I run the model with PADEL:
![PADEL_Results](https://github.com/ersilia-os/ersilia/assets/173019165/a97ac82a-272a-4975-9c74-6448500e3769)


This is how I have been trying to use RDKit, but I get different results:
 # Convert RDKit bit vector to a list of ints
    def bitvector_to_list(bitvector):
        return [int(bit) for bit in bitvector]

    def calculate_maccs_keys(smiles_list):
        maccs_keys = []
        for smi in smiles_list:
            mol = Chem.MolFromSmiles(smi)
            if mol is not None:
                maccs_key = MACCSkeys.GenMACCSKeys(mol)
                maccs_keys.append(bitvector_to_list(maccs_key))
            else:
                maccs_keys.append([0]*167)  # MACCS keys are 167 bits long
        return maccs_keys

    def desc_calc(smiles_list, output_file='descriptors_output.csv'):
        # Calculate MACCS fingerprints using RDKit
        maccs_keys = calculate_maccs_keys(smiles_list)
        
         # Create a DataFrame and name columns appropriately, save to CSV
        df = pd.DataFrame(maccs_keys, columns=[f'MACCSFP{i}' for i in range(167)]) 
        df.to_csv(output_file, index=False)
        return df

    # Model building section
    def build_model(input_data):
        # Reads in saved regression model
        load_model = pickle.load(open('Mpro_model.pkl', 'rb')) #  06.25.24 dtype error
        # Apply model to make predictions
        prediction = load_model.predict(input_data)
        st.header('**Prediction results**')
        prediction_output = pd.Series(prediction, name='pIC50')
        molecule_name = pd.Series(load_data[1], name='molecule_name')
        df = pd.concat([molecule_name, prediction_output], axis=1)
        st.write(df)
        st.markdown(filedownload(df), unsafe_allow_html=True)

These are the results I get when I use RDKit:
![RDKit_Results](https://github.com/ersilia-os/ersilia/assets/173019165/a31be569-6cc7-418b-bf40-ee9cbd6613c6)

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 
I am trying to reporduce the results but just with the molecule_name I cannot get the smiles. Where did you get the molecules from?

**Comment by GemmaTuron** [comment]
mm in any case it does seem the rdkit implementation and the PADEL descriptors differ slightly, quite surprising as the MACCS Keys are just substructure searchers in a way.
In any case, it must be due to the preprocessing that PADEL does vs the preprocessing that rdkit does. We can go ahead and use PADEL in the model, guess by just keeping the folder there it should work

**Comment by HarmonySosa** [comment]
Overall focus: Trying to get my code to run in the Ersilia framework

I transferred the code that I used to run the model into the Ersilia framework and I updated the environment, but I need to modify the code more to fit Ersilia. I am not sure how to use the input and output format in the main.py file, so I have been manually testing the code on an input file that I have, and I am now getting an index error "list index out of range" in the line input_order = [line.split()[1] for line in f] in desc_calc. 

This is my desc_calc function:

def desc_calc():

    bashCommand = "java -Xms2G -Xmx2G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/MACCSFingerprinter.xml -dir ./ -file descriptors_output.csv" # original bash command line
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()

    # Read original input file
    with open("molecule.smi", "r") as f:
        input_order = [line.split()[1] for line in f]

    descriptors_df = pd.read_csv("descriptors_output.csv")
    sorted_descriptors_df = descriptors_df.set_index('Name').reindex(input_order).reset_index() # sort output based on input to get correct ordering
    
    # Save the sorted output to a new file
    sorted_descriptors_df.to_csv("sorted_descriptors_output.csv", index=False)


This is the input I ran it on as a text file:
[C@]12([C@@]([H])([C@H](OC1=O)[C@@H](O)c(cc(C)cc3O)c34)[C@@]4(C5)[C@@H]5CC2)C CMNPD20798
CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@](C#N)([C@H](O)[C@@H]1O)C1=CC=C2N1N=CN=C2N)OC1=CC=CC=C1 DB14761
C1=CC(=C(C=C1C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O)O 5280445
C1=C(C=C(C(=C1O)O)O)C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O 4444991
C[C@@]12C(=C(O[C@@H]1O)C(=O)C(=C[C@](C=C)(C)CC3)[C@]34O)[C@]4(C)[C@H](O)CC2 CMNPD20802

I have not changed molecule.smi, which is based on the input, from my code that successfully runs the model outside of the Ersilia framework.

**Comment by GemmaTuron** [comment]
HI @HarmonySosa !

Thanks for the explanation. A few considerations:
If I run the following code with the example you suggest I get a nice output, I cannot reproduce your error:
```
with open("molecule.smi", "r") as f:
    input_order = [line.split()[1] for line in f]
print(input_order)
```
Output:
```
(base) gturon@pujarnol:~/github/ersilia-os$ python test.py
['CMNPD20798', 'DB14761', '5280445', '4444991', 'CMNPD20802']
```

If I understand it correctly you are trying to get the molecule names so that you can map them later on the descriptors right? That is a good idea but difficult to implement within Ersilia as Ersilia preprocesses the inputs.
The function that gets you a smiles list (in the right order) is:
```
# read SMILES from .csv file, assuming one column with header
with open(input_file, "r") as f:
    reader = csv.reader(f)
    next(reader)  # skip header
    smiles_list = [r[0] for r in reader]
```
So we need to work from that list (which only has smiles). If you think the only way is to assign an id to each smiles and then re-map it, you can take this smiles list and create a dataframe with an id column that you generate, something like
`ids = [f"smi_{x} for x in range(len(smiles_list)]`

**Comment by HarmonySosa** [comment]
Thank you, Gemma! I was able to resolve my errors so I can run my input and see the pIC50 values in the result, but  I am not sure that I understand how to use the Smiles list with the preprocessed inputs that you mentioned, so I likely still need to make adjustments to fit Ersilia. Can you explain a little more what you mean by creating the ids dataframe? This is the output that I currently get when I use Padel and print my dataframe:
    molecule_name     pIC50
0       DB14761  5.707753
1       5280445  5.194536
2       4444991  5.194536
3    CMNPD20802  5.095158

The output matches what I got when I ran the model locally, but I am not sure if this fits Ersilia properly.

**Comment by GemmaTuron** [comment]
Wehn you use Ersilia, you will not be able to retain the ID colum, as you can see from the code snippet that I passed to you the input file will only provide you with a list of smiles. So, if you need the ids to make sure the rearrangement is correct, you'll need to create those.
Try the model within Ersilia and you'll understand better. Remember to use the repo_path flag.

**Comment by GemmaTuron** [comment]
@HarmonySosa 

Can you update your code so I can see what you are writing to help you out? I see you have not yet pushed to github: https://github.com/HarmonySosa/eos3nn9

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

Just to confirm next steps:

- [ ] Contact the authors to let them know running the same molecules several times provides different outputs due to a rearrangement of the descriptors per molecule
- [ ] Understand if the rearrangement is due to the PADEL descriptors or the implementation in streamlit only (that would be ideal, but I think the problem is with the PADEL descriptors themselves as you point out) Just can you confirm that you still observe this effect when running the code not via Streamlit?
- [ ] Define a way to make sure the results are outputed in the same original order (you already did that actually). IF this is based on using an ID per SMILES ¡, you will need to do something like below in the `main.py` file for ersilia:

```
# read SMILES from .csv file, assuming one column with header
with open(input_file, "r") as f:
    reader = csv.reader(f)
    next(reader)  # skip header
    smiles_list = [r[0] for r in reader]
ids = [f"smi_{x} for x in range(len(smiles_list)]
df = pd.DataFrame({"id":ids, "smiles":smiles})

# here function to convert the smiles to descriptors

# here function to re-arrange descriptors ensuring order

# here function to obtain the predictions

# and if we are 100% sure the predictions are in the right order corresponding to the molecules in smiles_list, and that the predictions are in a list format:
# write output in a .csv file
with open(output_file, "w") as f:
    writer = csv.writer(f)
    writer.writerow(["value"])  # header, change as needed
    for o in outputs:
        writer.writerow([o])
```

Something like this should work!

**Comment by HarmonySosa** [comment]
Hi Gemma, thank you for the clarification! In response to the next steps,
- I contacted the authors after our meeting a few days ago, but I am still waiting for a response.
- I verified that the rearrangement is due to the PADEL descriptors themselves
- I am printing the SMILES in the proper order, but I am not following the Ersilia structure; this is what I am currently working on

I pushed the code so you can hopefully see it. The code currently doesn’t use the proper format you mentioned, but I was just trying to get code that worked and gave me an output that matched. Now, I am trying to adjust the code based on your suggestions to fit the Ersilia format.
Just to clarify, what is the desired output that I should have? Currently, my output is a printed table of the pIC50 values with the molecule name. Is this the proper format? 
Thanks for your help!

**Comment by GemmaTuron** [comment]
Hi Harmony,

The output is dealt with from the Ersilia side. From the code I shared you will see you only need to pass the list of outputs in this case, the pIC50, in the same order as the molecules were inputed. It will be written in a csv file that then Ersilia parses.

**Comment by HarmonySosa** [comment]
Hi! I changed main.py to use absolute paths and adjusted it so that it gives the desired pIC50 outputs when I use an input in a single column. I am trying to see if I can transfer all of the files that I have been using to the GitHub model. I have the Mpro pkl file in the checkpoints folder on my machine, and I also use the PaDEL-Descriptor folder, but I do not see these in the GitHub. Is there a way to add these files?

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa

If I understand correctly, you now have the necessary files somewhere not in your github folder? Or they are in your local GitHub folder but when you push it to your fork they do not appear online?
If they are in your github folder locally, you simply need to do a `git push`. Check if any error message is appearing (i,e files too large)

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron , I had the files on my Ubuntu machine but not on github because I kept getting errors when I tried to push them, including an error about the file size, but I think I have managed to get the PaDEL Descriptor folder in the github. I am just resolving conflicts between my Ubuntu and remote repos so I can add the remaining files, so I think it is figured out now!

**Comment by HarmonySosa** [comment]
Hi, I updated main.py to get rid of the filedownload function, as per Miquel’s suggestion, so main.py seems alright for now. Is it possible to verify the next steps in incorporating the model?

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

The code looks good, well done. A few suggestions:

- Move the PAdel folder inside framework and amend the path to there in main.py
- The temporal folder it is not actually a temporal folder, it is safer to create one for real: `tempfile.mkdtemp(prefix="ersilia-")` we like to use the prefix ersilia to ensure they will eventually be all removed.  And you can close it with something like `shutil.rmtree`


Once this is done, you simply have to make sure all the other files (particularly the `metadata.json`) is properly complete, and try to fetch the model locally inside Ersilia using the `repo_path` flag. If that works you should be ready to open a PR and merge the code!

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron, I made the changes you suggested and verified that I have the most recent version of Ersilia. I have been working through the fetch errors when I use the repo_path flag and this is what I have now:
[eos3nn9_fetch_error_180724.txt](https://github.com/user-attachments/files/16301973/eos3nn9_fetch_error_180724.txt)

I am going to go through the Ersilia troubleshooting guide again in case I missed anything, but I would appreciate it if you have any ideas. Thanks!

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

From this line: `/bin/sh: 1: bentoml: not found` I suspect something might not be working properly with your Ersilia installation.
- Have you first made sure the model works using the `bash run.sh` first?
- Is it an Ubuntu, Mac or Windows machine? Remember that windows does not work with Ersilia
- Did you figure out the problems you were indicating in the eos1pu1 issue? 
- Can you confirm ersilia works fine by testing another model¿

Remember in CodeSpaces you can use it as your own system, so you can open a codespace from Ersilia, git clone locally the repository you have forked (with all files) and test it there (still using the repo path, or the run.sh file)

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron, thank you for the help! I have tested that the model works with the run.sh command. I am using Ubuntu on a Windows machine, but I haven't been able to successfully fetch another model, including eos1pu1. I am trying to use CodeSpaces now to see if it works, and I will try reinstalling Ersilia again if it doesn't work.

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron ,
I tried using the CodeSpace but ended up reinstalling Ersilia. I am running Ubuntu and I now get this error:
[err.txt](https://github.com/user-attachments/files/16315194/err.txt)


I can access the url to get:
![eos3nn9_url_ss](https://github.com/user-attachments/assets/7ad788c3-572e-4fd6-9f14-64013ad937a0)

As such, I know it is loading this far to be able to see the url, but it is failing on the join. The error suggests a path problem, but I have been testing that and I do not see where it is. Do you have any suggestions?
Thanks!

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa ,

A few questions:
- Are you able to run any model on Ersilia in your system? Please try eos3b5e to ensure ersilia is working before using any new model that might be failing for other reasons
- What happened when you tried the CodeSpaces? Did it work? When you say you tried is that you did not succeed to use codespaces or that it did not work?
- What is the output you get with run.sh?

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron, to answer your question,
I get this output when I try to run another model on my system:
[eos3b5e_error_220724.txt](https://github.com/user-attachments/files/16334840/eos3b5e_error_220724.txt)

I wasn't able to get the CodeSpaces set up properly, but I will try again to install everything it needs to run.

When I run run.sh, I get the proper pIC50 values in order as expected:
![image](https://github.com/user-attachments/assets/437328c4-49b3-4010-8f96-55c2dd1bac04)

Thank you for your help!

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

For codespaces, you only need to open it in the ersilia repository, and it will already have ersilia installed

**Comment by HarmonySosa** [comment]
Thanks @GemmaTuron, I was confused because I thought I had to get Pandas and the other requirements on CodeSpaces as well. When I open a codespace and run ersilia -v fetch eos3b5e, I get this:
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

No module named 'pyairtable'

**Comment by GemmaTuron** [comment]
I just tried in the codespaces and it worked fine:
`(base) root@codespaces-a68f93:/workspaces/ersilia# ersilia -v fetch eos3b5e`

**Comment by GemmaTuron** [comment]
> Hi @GemmaTuron, to answer your question, I get this output when I try to run another model on my system: [eos3b5e_error_220724.txt](https://github.com/user-attachments/files/16334840/eos3b5e_error_220724.txt)
> 
> I wasn't able to get the CodeSpaces set up properly, but I will try again to install everything it needs to run.
> 
> When I run run.sh, I get the proper pIC50 values in order as expected: ![image](https://private-user-images.githubusercontent.com/173019165/350994326-437328c4-49b3-4010-8f96-55c2dd1bac04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjAyMDgsIm5iZiI6MTcyMTY1OTkwOCwicGF0aCI6Ii8xNzMwMTkxNjUvMzUwOTk0MzI2LTQzNzMyOGM0LTQ5YjMtNDAxMC04Zjk2LTU1YzJkZDFiYWMwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNDUxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDE3MjUwZDdjYjdlMGQ5NDk1OTRiZjAxYzJjNGQ5N2ViNzBmNWU5YmM5OWMwZGU1ZWZiOTkxNzMxOGMwMmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZ7KCeJjvvHB-A-cFMLBmKGweWUuMnjdqTxQeT-YDmI)
> 
> Thank you for your help!

for your local system, are you using a WSL? It clearly seems ersilia is not properly installed...

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron,  just to update my progress, I have resolved the java error and some path errors, but I have not gotten output yet when I try to fetch the model. 
 I have been using CodeSpaces because I am still getting the join error I showed in the meeting earlier when I don’t use the codespace, even after creating a new environment and reinstalling everything so that Ersilia should not be corrupted. I will try to figure this out, but for now I am going to continue using the codespace because it works when I run other models.

Currently, I am getting an error that I think is another path issue. I will begin tomorrow by looking at this issue:
[eos3nn9_fetch_error_220724.txt](https://github.com/user-attachments/files/16343605/eos3nn9_fetch_error_220724.txt)

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

Seems the paths to the temporal files are not well specified indeed:
```
Detailed error:
Model API eos3nn9:run did not produce an outputError: Could not find or load main class padeldescriptor.PaDELDescriptorApp
call from main code: /root/eos/repository/eos3nn9/20240723034821_9DB168/eos3nn9/artifacts/framework/code
Traceback (most recent call last):
  File "/root/eos/repository/eos3nn9/20240723034821_9DB168/eos3nn9/artifacts/framework/code/main.py", line 65, in <module>
    desc_calc()
  File "/root/eos/repository/eos3nn9/20240723034821_9DB168/eos3nn9/artifacts/framework/code/main.py", line 37, in desc_calc
    descriptors_df = pd.read_csv( f"{tmp_folder}/descriptors_output.csv" )
  File "/root/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/root/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/root/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/root/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ersilia-b0aakjxr/descriptors_output.csv'
```

This could be easier to debug locally than in Codespaces. Can you please attach as a txt file the conda list of your ersilia environment in your local?

**Comment by HarmonySosa** [comment]
Sure, here is the conda list of my ersilia environment:
[ersilia_conda_list.txt](https://github.com/user-attachments/files/16350098/ersilia_conda_list.txt)

I have a separate environment for the model where I downloaded everything that was in the requirements file:
[model_conda_list.txt](https://github.com/user-attachments/files/16350217/model_conda_list.txt)

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron,
I was able to fetch and run the model, so I will open a PR. If there is anything I am missing, let me know. Thanks for your help!

**Comment by HarmonySosa** [comment]
Hi, does this mean that the metadata is incorrect? I am unsure of the "output" in the metadata - I have it as "score" currently.  
![image](https://github.com/user-attachments/assets/ebb3efd3-23bd-4772-af65-bf04a633c071)

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

The metadata format is specified here: https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/incorporate-models/model-template#the-metadata.json-file
If you look at the action, it is complaining about the tags. Only a few are in the accepted list.
```
Hints:
Tags must be in list format and they must be accepted our team. This means that only tags that are already available in Ersilia are allowed. If you want to include a new tag, please open a pull request (PR) on the 'tag.txt' file from the Ersilia repository.

Traceback (most recent call last):
  File "/home/runner/work/eos3nn9/eos3nn9/update_metadata_to_airtable.py", line 14, in <module>
    data = rm.read_information(org=user_name, branch=branch)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/hub/content/card.py", line 463, in read_information
    bi.from_dict(data)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/hub/content/card.py", line 409, in from_dict
    self.tag = data["Tag"]
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/hub/content/card.py", line 254, in tag
    raise TagBaseInformationError
ersilia.utils.exceptions_utils.card_exceptions.TagBaseInformationError: Ersilia exception class:
TagBaseInformationError

Detailed error:
Wrong Ersilia model tag

Hints:
Tags must be in list format and they must be accepted our team. This means that only tags that are already available in Ersilia are allowed. If you want to include a new tag, please open a pull request (PR) on the 'tag.txt' file from the Ersilia repository.
```

**Comment by HarmonySosa** [comment]
Thanks @GemmaTuron 

I am getting this error:
[PR_error_padel_240724.txt](https://github.com/user-attachments/files/16364381/PR_error_padel_240724.txt)

I can see that the Padel descriptor folder is in framework, and I think that the path to the padel folder that I wrote in main.py is correct, assuming it is run from within the code directory. Do you have an idea why the test is unable to find the padel descriptor?

**Comment by GemmaTuron** [comment]
Hi @HarmonySosa 

Does the model work with `--repo_path` flag inside Ersilia locally? Indeed it seems the descriptors file is not being found

**Comment by HarmonySosa** [comment]
Yes, I can successfully fetch and run the model locally when I use the --repo_path flag.

**Comment by GemmaTuron** [comment]
mmm are all changes pushed to your fork? I have tried in my local (Ubutnu) and it crashes with the same error so I am curious to understand how are you making it work locally. Is it in your WSL and no differences with the code int he fork?

**Comment by GemmaTuron** [comment]
Also with the bash run.sh command:
```
(eos3nn9) gturon@pujarnol:~/github/ersilia-os/eos3nn9/model/framework$ bash run.sh . ~/osm.csv out.csv
Error: Could not find or load main class padeldescriptor.PaDELDescriptorApp
Caused by: java.lang.NoClassDefFoundError: org/jdesktop/application/SingleFrameApplication
Traceback (most recent call last):
  File "./code/main.py", line 62, in <module>
    desc_calc()
  File "./code/main.py", line 34, in desc_calc
    descriptors_df = pd.read_csv( f"{tmp_folder}/descriptors_output.csv" )
  File "/home/gturon/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/gturon/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/gturon/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/home/gturon/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/gturon/miniconda3/envs/eos3nn9/lib/python3.7/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ersilia-k0kcc3lo/descriptors_output.csv'
```

**Comment by GemmaTuron** [comment]
I've also noticed that openjdk seems to install an old version (11) which might be the cause of the problem, can you dig into it a bit?

**Comment by HarmonySosa** [comment]
I don't see any differences in the code in the fork, and I pushed the code to make sure everything was updated. When I run it with the --repo_path flag, I get an output:
![image](https://github.com/user-attachments/assets/ea8091bf-4e1b-4bbc-aa55-b6e267bcea9d)

I will look into the openjdk version to see if that is causing the error. Thank you!

**Comment by HarmonySosa** [comment]
Hi @GemmaTuron ,
I am still having issues with the pull request. I tried to test with openjdk version 17.0.11, but I haven’t seen a difference. Since I was getting errors that the test couldn’t find the padel jar file and padeldescriptor.PaDEL-DescriptorApp, I added a directory for the jar file contents and a path to explicitly find this. I think this has worked to allow it to access the files, but I am getting an error that I think means it is not writing or finding the intermediary output file from the padel line. This is the error:
![error_output](https://github.com/user-attachments/assets/ba3db5de-05ef-4ca2-a715-1eed69c412cc)


I am considering giving an explicit temp directory to write to that, in case it is an issue of not being able to find the file. However, I still don’t understand why these errors are happening, since I can see the location of the files as I expect, and I can run the model properly with the –repo_path flag on my machine.

**Comment by HarmonySosa** [comment]
Hi, to update the status of the model, the PR is succeeding until the last step (adding to Docker) with an error “Java not found” which is believed to be a path error. I have tried running a simple docker image and installing openjdk in the base environment to see if I can reproduce the error. I have also tried installing openjdk in an environment that is more similar to the environment I use when I run my model in Ersilia(same Python version, etc) but so far the installation has worked and I haven’t seen the error reproduced. I am still exploring this and will check with Dhanshree for ideas.

**Comment by miquelduranfrigola** [comment]
Thanks @HarmonySosa - great job. @DhanshreeA is it possible that the `conda-pack` step is not conserving the shortcut to the `java` executable? In that case, we should explicitly find the `java` executable in the corresponding environment folder and run it from there. Thoughts?

**Comment by HarmonySosa** [comment]
Hi @DhanshreeA, to update you before our meeting tomorrow, this is the output I currently get when I run the ersilia_model_pack command from the ersilia-pack readme:
[results_20240801.txt](https://github.com/user-attachments/files/16464427/results_20240801.txt)

**Comment by HarmonySosa** [comment]
Hi @miquelduranfrigola and @GemmaTuron,

To keep you updated, here are some of the highlights that Dhanshree and I talked about in our meeting today from using ersilia-pack:
- PyYAML was not installed, even through fastapi - similar issue with uvicorn
- ersiila_model_serve bundle path expected $BUNDLE_PATH/MODEL_ID but this wasn’t clear from the readme
- Resolved numpy version mismatches 
- Resolved key error with 'Card' vs 'card' in packer.py function _get_input_schema
- The install.sh bash script was not closing an if block correctly
- Examples in app.py were being misread; inconsistency in Input and output file names

I am working on finishing these changes to serve the model.

**Comment by DhanshreeA** [comment]
> Thanks @HarmonySosa - great job. @DhanshreeA is it possible that the `conda-pack` step is not conserving the shortcut to the `java` executable? In that case, we should explicitly find the `java` executable in the corresponding environment folder and run it from there. Thoughts?

This is now resolved @miquelduranfrigola - and conda-pack is preserving the java executable in the standalone environment. The issue was with conda being unable to resolve the given openjdk version harmoniously with other libxxx dependencies in the same environment. Downgrading openjdk to 8.0.421 seemed to have worked.

**Comment by miquelduranfrigola** [comment]
Amazing @HarmonySosa and @DhanshreeA ! So we can close the issue?

**Comment by DhanshreeA** [comment]
Good from my side @miquelduranfrigola !
