### ISSUE TITLE
🐛 Bug: Inconsistent Output Error with model eos4tcc

### ISSUE THREAD

**Issue by kurysauce** [ersilia-os/ersilia#1221]
### Describe the bug.

When model is tested using the command `ersilia -v test eos4tcc`, the `check_consistent_output` method runs the model twice with the same input and compares the outputs. An error is raised stating that both outputs have a greater than 5% difference, which is unexpected.  

Log output:
```
**20:35:56 | DEBUG    | Outputs that raise error: 0.43146425, 0.53953654. Difference: 0.10807228999999996
20:35:56 | DEBUG    | Percentage difference for outcome: 22.25997982967655**


**{'input': {'key': 'XNSAINXGIQZQOO-SRVKXCTJSA-N', 'input': 'NC(=O)[C@@H]1CCCN1C(=O)[C@H](Cc1c[nH]cn1)NC(=O)[C@@H]1CCC(=O)N1', 'text': 'NC(=O)[C@@H]1CCCN1C(=O)[C@H](Cc1c[nH]cn1)NC(=O)[C@@H]1CCC(=O)N1'}, 'output': {'outcome': [0.43146425, 0.22777487, 0.017527986]}}
{'input': {'key': 'XNSAINXGIQZQOO-SRVKXCTJSA-N', 'input': 'NC(=O)[C@@H]1CCCN1C(=O)[C@H](Cc1c[nH]cn1)NC(=O)[C@@H]1CCC(=O)N1', 'text': 'NC(=O)[C@@H]1CCCN1C(=O)[C@H](Cc1c[nH]cn1)NC(=O)[C@@H]1CCC(=O)N1'}, 'output': {'outcome': [0.53953654, 0.22860871, 0.019828169]}}**


{'input': {'key': 'IBAQFPQHRJAVAV-ULAWRXDQSA-N', 'input': 'OCCN1C[C@H](O)[C@@H](O)[C@H](O)[C@H]1CO', 'text': 'OCCN1C[C@H](O)[C@@H](O)[C@H](O)[C@H]1CO'}, 'output': {'outcome': [0.44287112, 0.22686765, 0.019868646]}}
{'input': {'key': 'IBAQFPQHRJAVAV-ULAWRXDQSA-N', 'input': 'OCCN1C[C@H](O)[C@@H](O)[C@H](O)[C@H]1CO', 'text': 'OCCN1C[C@H](O)[C@@H](O)[C@H](O)[C@H]1CO'}, 'output': {'outcome': [0.5292925, 0.2278303, 0.021311654]}}


{'input': {'key': 'HBDSHCUSXQATPO-BGBJRWHRSA-N', 'input': 'O\\N=C1\\C(\\Nc2ccccc\\12)=C1\\C(=O)Nc2ccccc12', 'text': 'O\\N=C1\\C(\\Nc2ccccc\\12)=C1\\C(=O)Nc2ccccc12'}, 'output': {'outcome': [0.42732492, 0.22778949, 0.01692879]}}
{'input': {'key': 'HBDSHCUSXQATPO-BGBJRWHRSA-N', 'input': 'O\\N=C1\\C(\\Nc2ccccc\\12)=C1\\C(=O)Nc2ccccc12', 'text': 'O\\N=C1\\C(\\Nc2ccccc\\12)=C1\\C(=O)Nc2ccccc12'}, 'output': {'outcome': [0.52886117, 0.23121828, 0.017948776]}}


{'input': {'key': 'NNAIYOXJNVGUOM-UHFFFAOYSA-N', 'input': 'CCNC(=O)N1CCN(CCCC(c2ccc(F)cc2)c2ccc(F)cc2)CC1', 'text': 'CCNC(=O)N1CCN(CCCC(c2ccc(F)cc2)c2ccc(F)cc2)CC1'}, 'output': {'outcome': [0.43095407, 0.23003721, 0.015195469]}}
{'input': {'key': 'NNAIYOXJNVGUOM-UHFFFAOYSA-N', 'input': 'CCNC(=O)N1CCN(CCCC(c2ccc(F)cc2)c2ccc(F)cc2)CC1', 'text': 'CCNC(=O)N1CCN(CCCC(c2ccc(F)cc2)c2ccc(F)cc2)CC1'}, 'output': {'outcome': [0.532388, 0.22927731, 0.019673761]}}


{'input': {'key': 'IMXHGCRIEAKIBU-UHFFFAOYSA-N', 'input': 'COC(=O)Nc1ccc(cc1)-c1nc(N2CCOCC2)c2cnn(C3CCN(CC3)C(=O)OC)c2n1', 'text': 'COC(=O)Nc1ccc(cc1)-c1nc(N2CCOCC2)c2cnn(C3CCN(CC3)C(=O)OC)c2n1'}, 'output': {'outcome': [0.44150674, 0.229045, 0.017533528]}}
{'input': {'key': 'IMXHGCRIEAKIBU-UHFFFAOYSA-N', 'input': 'COC(=O)Nc1ccc(cc1)-c1nc(N2CCOCC2)c2cnn(C3CCN(CC3)C(=O)OC)c2n1', 'text': 'COC(=O)Nc1ccc(cc1)-c1nc(N2CCOCC2)c2cnn(C3CCN(CC3)C(=O)OC)c2n1'}, 'output': {'outcome': [0.5253863, 0.22625948, 0.023096036]}}


20:35:56 | ERROR    | Ersilia exception class:
InconsistentOutputs

Detailed error:
Model outputs are inconsistent, meaning the outputs do not fit the 5% similarity threshold.

Hints:
Observe the output comparisons for each smiles input above.

🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

Ersilia exception class:
InconsistentOutputs

Detailed error:
Model outputs are inconsistent, meaning the outputs do not fit the 5% similarity threshold.

Hints:
Observe the output comparisons for each smiles input above.
```

### Describe the steps to reproduce the behavior

0. Delete the model(`ersilia delete eos4tcc`) `eos4tcc` if the model was fetched without the `--from_github` flag.
1. Fetch the model: `ersilia fetch eos4tcc --from_github`
2. Serve the model: `ersilia serve eos4tcc`
3. Run the test command with the verbose flag: `ersilia -v test eos4tcc`

### Operating environment

MacOS 14.0, GitHub Codespace

**Comment by kurysauce** [comment]
Verifying model outputs on Ersilia maintained compound input data @GemmaTuron @miquelduranfrigola

**Comment by miquelduranfrigola** [comment]
Thanks @kurysauce - just to keep track of things, the maintained inputs are available [here](https://github.com/ersilia-os/ersilia-model-hub-maintained-inputs/blob/main/compound/single/inp-000.csv).

**Comment by kurysauce** [comment]
@miquelduranfrigola @GemmaTuron 
<img width="984" alt="output_0_and_output_1" src="https://github.com/user-attachments/assets/5e27a7d6-eacf-4602-906e-167018a49983">
<img width="980" alt="outout_0_and_output_2" src="https://github.com/user-attachments/assets/629cac2b-d790-4940-98f8-c5ba3c1453c8">


<img width="743" alt="Screenshot 2024-08-05 at 3 54 31 PM" src="https://github.com/user-attachments/assets/715629c5-f79d-489b-b8ce-d2fbbd4080d3">

I ran a correlation analysis and it seems that the **score** and **alea** across different outputs are highly correlated with one another. There is a moderate correlation with the **epi** value across the outputs. What should we do with this info?

**Comment by miquelduranfrigola** [comment]
Hello @kurysauce this is a very good and insightful analysis. Many thanks for this.
There are a few ways forward, but first, can we address the following?
- [ ] Can we check and explain in this issue what is the meaning of `score`, `alea` and `epis`? This is not standard terminology and it will help all of us decide what to do next.
- [ ] Can you paste here a few scatter plots? For example: alea_0 vs alea_1, alea_0 vs score_1, and epis_0 vs epis_2? I'd like to see the dynamic range of the values, i.e. are we dealing with values ranging from 0 to 1, or is the range more narrow?
- [ ] In the publication, can you identify some "positive controls" and "negative controls"? That is, molecules that we expect to give high values (in any of the outputs - score, alea, epis), and molecules that we expect to give low values? Running predictions on these control samples will help us gain more confidence in our anlalysis.
What do you think? Does all of this sound reasonable?

**Comment by kurysauce** [comment]
> Hello @kurysauce this is a very good and insightful analysis. Many thanks for this.
> 
> 
> 
> There are a few ways forward, but first, can we address the following?
> 
> 
> 
> - [ ] Can we check and explain in this issue what is the meaning of `score`, `alea` and `epis`? This is not standard terminology and it will help all of us decide what to do next.
> 
> - [ ] Can you paste here a few scatter plots? For example: alea_0 vs alea_1, alea_0 vs score_1, and epis_0 vs epis_2? I'd like to see the dynamic range of the values, i.e. are we dealing with values ranging from 0 to 1, or is the range more narrow?
> 
> - [ ] In the publication, can you identify some "positive controls" and "negative controls"? That is, molecules that we expect to give high values (in any of the outputs - score, alea, epis), and molecules that we expect to give low values? Running predictions on these control samples will help us gain more confidence in our anlalysis.
> 
> 
> 
> What do you think? Does all of this sound reasonable?

Yes, I can get to work on it.

**Comment by kurysauce** [comment]
> > Hello @kurysauce this is a very good and insightful analysis. Many thanks for this.
> > There are a few ways forward, but first, can we address the following?
> > 
> > * [ ]  Can we check and explain in this issue what is the meaning of `score`, `alea` and `epis`? This is not standard terminology and it will help all of us decide what to do next.
> > * [ ]  Can you paste here a few scatter plots? For example: alea_0 vs alea_1, alea_0 vs score_1, and epis_0 vs epis_2? I'd like to see the dynamic range of the values, i.e. are we dealing with values ranging from 0 to 1, or is the range more narrow?
> > * [ ]  In the publication, can you identify some "positive controls" and "negative controls"? That is, molecules that we expect to give high values (in any of the outputs - score, alea, epis), and molecules that we expect to give low values? Running predictions on these control samples will help us gain more confidence in our anlalysis.
> > 
> > What do you think? Does all of this sound reasonable?
> 
> Yes, I can get to work on it.

1. `score` represents the prediction score from the model, indicating the likelihood that a molecule blocks the hERG channel. Higher scores imply a higher likelihood of hERG channel blocking.
`alea` stands for Aleatoric Uncertainty. The authors used this value to measure the uncertainty existing in the data due to noise and variability.
`epis` stands for Epistemic Uncertainty. This measures the uncertainty in the model due to a lack of knowledge or data, which reflects on the model's parameters and structure.

2.
<img width="1416" alt="Screenshot 2024-08-06 at 2 28 07 PM" src="https://github.com/user-attachments/assets/bf6b0220-7990-43a8-83c1-18dd66f8174f">

It seems that the values are narrows, but still indicate a positive correlation.

3. From the introduction of the paper, confirmed molecules that will give a high `score` are Astemizole, Terfenadine, and Cisapride. Molecules that will give a low `score` are Fexofenadine, Lisinopril, or other drugs that are verified to not block hERG channels.

**Comment by miquelduranfrigola** [comment]
Thanks @kurysauce , this is outstanding work.

OK, I think that we can be confident about this model.
I do think we should keep score, alea and epis. Knowing the uncertainty underlying a prediction is a luxury that we do not have often. It is great that this model is offering this. So, I would keep the three outputs.

Now we need to think how adapt/modify the test command so that a case like this passes the test. The 5% variability threshold was probably too simple. Can we brainstorm a solution? One possible solution would be to measure correlations, as you've done, and set a cutoff of Spearman's correlation. For example, we could raise an error if rho is less than a certain value (0.5?) and a warning if it is less than a higher value (0.8?).

What are your thoughts?

**Comment by kurysauce** [comment]
> Thanks @kurysauce , this is outstanding work.
> 
> OK, I think that we can be confident about this model. I do think we should keep score, alea and epis. Knowing the uncertainty underlying a prediction is a luxury that we do not have often. It is great that this model is offering this. So, I would keep the three outputs.
> 
> Now we need to think how adapt/modify the test command so that a case like this passes the test. The 5% variability threshold was probably too simple. Can we brainstorm a solution? One possible solution would be to measure correlations, as you've done, and set a cutoff of Spearman's correlation. For example, we could raise an error if rho is less than a certain value (0.5?) and a warning if it is less than a higher value (0.8?).
> 
> What are your thoughts?
> 
> Also, thanks for your point 3 - great that you checked these drugs.

These are good ideas! I agree that the Spearman's correlation would be a good measurement to identify the correlation between outputs.

 I still believe that we should have some measurement of differences between the two model runs because this is an quick and intuitive metric for users to understand and help debug their model incorporations. So, I propose that we calculate the Mean Relative Absolute Error as opposed to the percentage difference. I notice that model outputs for `float` types are relatively small, so there is greater sensitivity in the error percentage difference calculations. The MRAE normalizes the absolute error with respect to the actual value, making the metric a bit more robust than what we have right now. 
 
 I think having these two metrics would be helpful for the users in debugging and understanding the model outputs in context. 
 
 What do you think, @miquelduranfrigola ?

**Comment by kurysauce** [comment]
> > Thanks @kurysauce , this is outstanding work.
> > OK, I think that we can be confident about this model. I do think we should keep score, alea and epis. Knowing the uncertainty underlying a prediction is a luxury that we do not have often. It is great that this model is offering this. So, I would keep the three outputs.
> > Now we need to think how adapt/modify the test command so that a case like this passes the test. The 5% variability threshold was probably too simple. Can we brainstorm a solution? One possible solution would be to measure correlations, as you've done, and set a cutoff of Spearman's correlation. For example, we could raise an error if rho is less than a certain value (0.5?) and a warning if it is less than a higher value (0.8?).
> > What are your thoughts?
> > Also, thanks for your point 3 - great that you checked these drugs.
> 
> These are good ideas! I agree that the Spearman's correlation would be a good measurement to identify the correlation between outputs.
> 
> I still believe that we should have some measurement of differences between the two model runs because this is an quick and intuitive metric for users to understand and help debug their model incorporations. So, I propose that we calculate the Mean Relative Absolute Error as opposed to the percentage difference. I notice that model outputs for `float` types are relatively small, so there is greater sensitivity in the error percentage difference calculations. The MRAE normalizes the absolute error with respect to the actual value, making the metric a bit more robust than what we have right now.
> 
> I think having these two metrics would be helpful for the users in debugging and understanding the model outputs in context. I implemented them on my [updated fork](https://github.com/kurysauce/ersilia_test/blob/master/ersilia/publish/test.py) if you want to take a look. What do you think, @miquelduranfrigola ?

With the updated code, the `check_consistent_output` method passes. However, when executing the `run_bash` method, there is a problem in running the code local to the `eos4tcc` model incorporation I believe. I don't think this relates to the written test cases since the script is able to pass in other models. 

Log:
```
01:27:31 | DEBUG    | Changing directory to: /root/eos/dest/eos4tcc/model/framework
01:27:31 | DEBUG    | Script path: /tmp/tmpcjg9qyfd/script.sh
01:27:31 | DEBUG    | bash output path: /tmp/tmpcjg9qyfd/bash_output.csv
01:27:31 | DEBUG    | Output log path: /tmp/tmpcjg9qyfd/output.txt
01:27:31 | DEBUG    | Error log path: /tmp/tmpcjg9qyfd/error.txt
Executing 'bash run.sh'...
Bash execution completed!

01:27:33 | DEBUG    | WARNING: Bash output file not found when reading the path: /tmp/tmpcjg9qyfd/bash_output.csv 
 Ersilia and Bash comparison will raise an error
Captured Error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/eos4tcc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./code/main.py", line 188, in <module>
    test_data = load_data(df, atom_featurizer, bond_featurizer)
  File "./code/main.py", line 52, in load_data
    test_g = [smiles_to_bigraph(smi, node_featurizer=atom_featurizer, edge_featurizer=bond_featurizer) for smi in df['smiles']]
  File "/root/miniconda3/envs/eos4tcc/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/root/miniconda3/envs/eos4tcc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'smiles'

🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

[Errno 2] No such file or directory: '/tmp/tmpcjg9qyfd/bash_output.csv'
```

**Comment by miquelduranfrigola** [comment]
Hi @kurysauce 
In line 724 of [this script](https://github.com/kurysauce/ersilia_test/blob/master/ersilia/publish/test.py) we are creating a temporary script. Could you try to run that script manually? This will help us inspect the error easily.

**Comment by kurysauce** [comment]
> Hi @kurysauce In line 724 of [this script](https://github.com/kurysauce/ersilia_test/blob/master/ersilia/publish/test.py) we are creating a temporary script. Could you try to run that script manually? This will help us inspect the error easily.

Here are the relevant logs when running the test script:
06:21:37 | DEBUG    | Changing directory to: /root/eos/dest/eos4tcc/model/framework
06:21:37 | DEBUG    | Script path: /tmp/tmp5f62ujgh/script.sh
06:21:37 | DEBUG    | bash output path: /tmp/tmp5f62ujgh/bash_output.csv
06:21:37 | DEBUG    | Output log path: /tmp/tmp5f62ujgh/output.txt
06:21:37 | DEBUG    | Error log path: /tmp/tmp5f62ujgh/error.txt
Generated bash script content:

the temp script: 
    source /root/miniconda3/etc/profile.d/conda.sh     
    conda activate eos4tcc
    cd /root/eos/dest/eos4tcc/model/framework
    bash run.sh . /tmp/tmp5f62ujgh/example_file.csv /tmp/tmp5f62ujgh/bash_output.csv > /tmp/tmp5f62ujgh/output.txt 2> /tmp/tmp5f62ujgh/error.txt
    conda deactivate
    
   When I run `(ersilia) (.conda) (base) root@codespaces-659d6c:/workspaces/ersilia_test# ./manual_script.sh`

I get the error: `./manual_script.sh: line 4: /tmp/tmp5f62ujgh/output.txt: No such file or directory`

Which doesn't make sense to me because the logs indicate that the file does exist @miquelduranfrigola ?

**Comment by kurysauce** [comment]
> > Hi @kurysauce In line 724 of [this script](https://github.com/kurysauce/ersilia_test/blob/master/ersilia/publish/test.py) we are creating a temporary script. Could you try to run that script manually? This will help us inspect the error easily.
> 
> Here are the relevant logs when running the test script: 06:21:37 | DEBUG | Changing directory to: /root/eos/dest/eos4tcc/model/framework 06:21:37 | DEBUG | Script path: /tmp/tmp5f62ujgh/script.sh 06:21:37 | DEBUG | bash output path: /tmp/tmp5f62ujgh/bash_output.csv 06:21:37 | DEBUG | Output log path: /tmp/tmp5f62ujgh/output.txt 06:21:37 | DEBUG | Error log path: /tmp/tmp5f62ujgh/error.txt Generated bash script content:
> 
> the temp script: source /root/miniconda3/etc/profile.d/conda.sh conda activate eos4tcc cd /root/eos/dest/eos4tcc/model/framework bash run.sh . /tmp/tmp5f62ujgh/example_file.csv /tmp/tmp5f62ujgh/bash_output.csv > /tmp/tmp5f62ujgh/output.txt 2> /tmp/tmp5f62ujgh/error.txt conda deactivate
> 
> When I run `(ersilia) (.conda) (base) root@codespaces-659d6c:/workspaces/ersilia_test# ./manual_script.sh`
> 
> I get the error: `./manual_script.sh: line 4: /tmp/tmp5f62ujgh/output.txt: No such file or directory`
> 
> Which doesn't make sense to me because the logs indicate that the file does exist @miquelduranfrigola ?

CLOSING COMMENT: 
```
Traceback (most recent call last):
  File "./code/main.py", line 188, in <module>
    test_data = load_data(df, atom_featurizer, bond_featurizer)
  File "./code/main.py", line 52, in load_data
    test_g = [smiles_to_bigraph(smi, node_featurizer=atom_featurizer, edge_featurizer=bond_featurizer) for smi in df['smiles']]
  File "/root/miniconda3/envs/eos4tcc/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/root/miniconda3/envs/eos4tcc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'smiles'
```
I verified that the 'smiles' column exists in the main.py script and in the `load_data` function. Yet, this specific bug still remains. This causes the test module to fail because the bash output is unable to run. I verified that an output was produced by running the model locally and running the bash script generated locally as well.

**Comment by JoyProg** [comment]
Hi @DhanshreeA 

The issue is with how the example input is written to the file

```python
with open(ex_file, "w") as f:
    f.write("smiles")
    for item in input:
	      f.write(str(item) + "\n")
```
By adding a new line, it resolves the issue

```python
with open(ex_file, "w") as f:
    f.write("smiles\n")
    for item in input:
        f.write(str(item) + "\n")
```

I encountered some other issues which I have attempted to solve, but I need your input as this may or may not be the best approach or right context.

1. Not finding the [conda.sh](http://conda.sh/) file.
 Solution: The file was not in the default location so I searched for the conda.sh  file

```python
def _find_conda_sh():
            "Find the conda shell file necessary to activate the conda environment"
            try:
                result = subprocess.run(
                    ["conda", "info", "--base"], capture_output=True, text=True, check=True
                )
                base_path = result.stdout.strip()
                conda_sh_path = os.path.join(base_path, "etc", "profile.d", "conda.sh")
                if os.path.exists(conda_sh_path):
                    return conda_sh_path
                else:
                    raise FileNotFoundError(f"conda.sh not found at {conda_sh_path}")
            except subprocess.CalledProcessError as e:
                raise RuntimeError(f"Error running 'conda info --base': {e.stdout}") from e
            except Exception as e:
                raise RuntimeError(f"Could not locate conda.sh: {e}"
```
```
conda_sh = _find_conda_sh()
bash_script = """
    source {0}       
    conda activate {1}
    cd {2}
    bash run.sh . {3} {4} > {5} 2> {6}
    conda deactivate
    """.format(
                    conda_sh,
                    self.model_id,
                    run_path,
                    ex_file,
                    bash_output_path,
                    output_log,
                    error_log,
                )
```

2. Data type Conversion error in the updated_read_csv method
```
| DEBUG    | Processing line: CC(C)N(CC[C@H](c1ccccc1)c1cc(C)ccc1O)C(C)C,0.062391765,0.057316724,0.0011823076

 DEBUG    | Selected Values: ['CC(C)N(CC[C@H](c1ccccc1)c1cc(C)ccc1O)C(C)C', '0.062391765', '0.057316724', '0.0011823076'] and their type ['Float']
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

could not convert string to float: 'CC(C)N(CC[C@H](c1ccccc1)c1cc(C)ccc1O)C(C)C'
```

Solution: In this case, I assumed that if there are SMILES strings, they should remain unchanged, while the other columns contain numeric values (floats or integers) that need to be converted.
```
if self._output_type == ["Float"]:
    selected_values = [_safe_float_conversion(x) for x in selected_values]
    self.logger.debug(f"Converted to floats: {selected_values}")
elif self._output_type == ["Integer"]:
    selected_values = [_safe_int_conversion(x) for x in selected_values]
    self.logger.debug(f"Converted to integers: {selected_values}")

# helper methods
def _safe_float_conversion(x):
            if isinstance(x, (int, float)):
                return x
            try:
                return float(x)
            except ValueError:
                return x
            
        def _safe_int_conversion(x):
            if isinstance(x, (int, float)):
                return x
            try:
                return int(x)
            except ValueError:
                return x
```

I’d appreciate your input on whether this solves the issues (especially for the newer issues found) or if you have suggestions for improving it.

**Comment by JoyProg** [comment]
@DhanshreeA any feedback and can this issue be assigned to me if the solutions suffice?

**Comment by DhanshreeA** [comment]
Hi @JoyProg I have assigned the issue to you! Please create a PR in the model's repository.

**Comment by DhanshreeA** [comment]
Hi @JoyProg I'll provide feedback before EOD for sure. Meanwhile I need some further clarity on whether you actually used the ersilia test command for this model repository, and did you use the previous contributor's fork to work on this?

**Comment by JoyProg** [comment]
@DhanshreeA I ran `ersilia -v test eos4tcc` on the Ersilia main repository fork instead of the contributor's fork.

**Comment by JoyProg** [comment]
Update: I have been able to resolve this issue after updating to the latest version due to issue #1329. When I attempt to fetch the model, I get an error: `AttributeError: 'ModelURLResolver' object has no attribute '_read_json_file'`

**Comment by miquelduranfrigola** [comment]
Hi @DhanshreeA I am also getting this error

**Comment by GemmaTuron** [comment]
The error should be solved. I will fix this model so we can finally close this issue.

**Comment by GemmaTuron** [comment]
Update:

I aim to solve the current model incorporations before the end of the year. I'll tackle them after Mozilla Demo Day

**Comment by miquelduranfrigola** [comment]
Update:

I have tried to fetch this model from DockerHub and, indeed, it provides empty outputs on my Mac Mini

**Comment by GemmaTuron** [comment]
We are tackling this as part of the model reannotation, I'll close this issue!
