### ISSUE TITLE
🐛 Bug: When model is already fetched as Docker, Docker not active error when re-fetching from GitHub

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1408]
### Describe the bug.

I have a model fetched from DockerHub.
When I try to refetch, now from GitHub (but Docker is not active), I get the following error:

```
(ersilia) mduranfrigola@Miquels-MacBook-Pro ~ % ersilia -v fetch eos3b5e --from_github
⬇️  Fetching model eos3b5e: molecular-weight
09:12:50 | DEBUG    | Initialized with URL: None
09:12:50 | DEBUG    | Getting model source
09:12:50 | DEBUG    | Model getting fetched from GitHub
09:12:50 | DEBUG    | Starting fetching procedure
09:12:50 | DEBUG    | Fetching in your system, not from DockerHub
09:12:50 | DEBUG    | Model already exists in your local, skipping fetching
09:12:50 | DEBUG    | Running standard CSV example
09:12:50 | DEBUG    | /Users/mduranfrigola/eos/dest/eos3b5e/example_standard_input.csv
09:12:50 | DEBUG    | /Users/mduranfrigola/eos/dest/eos3b5e/example_standard_output.csv
09:12:50 | DEBUG    | Usage: ersilia [OPTIONS] COMMAND [ARGS]...

  🦠 Welcome to Ersilia! 💊

Options:
  --version      Show the version and exit.
  -v, --verbose  Show logging on terminal when running commands.
  -s, --silent   Do not echo any progress message.
  --help         Show this message and exit.

Commands:
  auth       Log in to ersilia to enter contributor mode.
  catalog    List a catalog of models
  close      Close model
  delete     Delete model from local computer
  example    Generate input examples for the model of interest
  fetch      Fetch model from Ersilia Model Hub
  info       Get model information
  inspect    Inspect model
  run        Run a served model
  sample     Sample inputs and model identifiers
  serve      Serve model
  test       Test a model
  uninstall  Uninstall ersilia

09:12:50 | DEBUG    | No need to use Conda!
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

Ersilia exception class:
DockerNotActiveError

Detailed error:
Docker is not active. Cannot serve model

Hints:
Please activate docker and try again

If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io

If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /Users/mduranfrigola/eos/current.log
09:12:51 | DEBUG    | File /Users/mduranfrigola/eos/dest/eos3b5e/example_standard_output.csv created successfully!
09:12:51 | DEBUG    | Removing log file: /Users/mduranfrigola/eos/dest/eos3b5e/standard_run.log
Traceback (most recent call last):
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/bin/ersilia", line 8, in <module>
    sys.exit(cli())
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/ersilia/cli/commands/__init__.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/ersilia/cli/commands/fetch.py", line 118, in fetch
    is_fetched = _fetch(mf, model_id)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/ersilia/cli/commands/fetch.py", line 15, in _fetch
    res = asyncio.run(mf.fetch(model_id))
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/ersilia/hub/fetch/fetch.py", line 257, in fetch
    self._standard_csv_example(model_id)
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/ersilia/hub/fetch/fetch.py", line 163, in _standard_csv_example
    ms.run()
  File "/Users/mduranfrigola/miniconda3/envs/ersilia/lib/python3.10/site-packages/ersilia/hub/fetch/register/standard_example.py", line 58, in run
    os.remove(run_log)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mduranfrigola/eos/dest/eos3b5e/standard_run.log'
```

The **expected behaviour** should be that the user is asked if they want to re-fetch, **or**, we could simply say: "Model is already fetch, please delete it first if you want to fetch it again".

### Describe the steps to reproduce the behavior

I previously did `ersilia -v fetch eos3b5e --from_dockerhub`.
Using ersilia v0.1.39, I simply did `ersilia -v fetch eos3b5e --from_github`. Docker is not active in my computer.

### Operating environment

Ubuntu 20.04 LTS

**Comment by DhanshreeA** [comment]
@miquelduranfrigola from the logs, I do see that the model is indeed already fetched, where it says: `09:12:50 | DEBUG    | Model already exists in your local, skipping fetching`.

I think there are different ways to handle this:
1. Stop the fetching process because the model is already fetched, and ask the user to delete it and try again - like you suggest.
2. Based on how the model was fetched, we can do a couple of different things - if the model was fetched from source A, and now the user is requesting source B, we can simply fetch again, and overwrite the previous source. For example, if a model was fetched from DockerHub, and now the user is requesting to fetch it from GitHub, we can compare the two sources and decide to overwrite and fetch again. The side effect would be that the model's image would continue to exist on the system so the user can switch to using the dockerhub fetched version if needed, and also the dest directory for the model will get populated in the EOS folder, so then the user could easily switch between the two modes. 

I prefer the second approach because it will avoid some steps and would make for a smarter user experience. What do you think?

**Comment by miquelduranfrigola** [comment]
I get your point. I leave it up to you to decide!

**Comment by DhanshreeA** [comment]
I will implement the second approach then.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Are you working on this? If so, please move the status to In Progress and add a deadline
