### ISSUE TITLE
🐛 Bug: Ersilia catalog outputing traceback error(pkg_resources.ContextualVersionConflict)

### ISSUE THREAD

**Issue by EstherIdabor** [ersilia-os/ersilia#313]
### Describe the bug.

running ersilia catalog after smooth installation of the Ersilia python package produces a traceback error:

Traceback (most recent call last):                                                                                                                                        
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master                                                                               ws.require(__requires__)                                                                                                                                              

File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require                                                                                     needed = self.resolve(parse_requirements(requirements))                                                                                                               

File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve                                                                                     raise VersionConflict(dist, req).with_context(dependent_req)                                                                                                        pkg_resources.ContextualVersionConflict: (importlib-metadata 1.5.0 (/usr/lib/python3/dist-packages), Requirement.parse('importlib-metadata>=3.6.0; python_version < "3.10"'), {'flask'})

![Screenshot (104)](https://user-images.githubusercontent.com/70244748/195244938-2ee54220-2a10-4e12-9deb-1a39f064901b.png)

### Describe the steps to reproduce the behavior

ersilia catalog

### Expected behavior.

output ersilia's model catalog

### Operating environment

Ubuntu 20.04.4 LTS

**Comment by GemmaTuron** [comment]
Hi @EstherIdabor 
Do other commands also crash or it is only the catalog? can you try
`ersilia --help`

**Comment by GemmaTuron** [comment]
@EstherIdabor  see my suggestions in #312 try and install it anew.

**Comment by EstherIdabor** [comment]
Thank you very much @GemmaTuron

**Comment by GemmaTuron** [comment]
Hi @EstherIdabor is this issue solved?

**Comment by EstherIdabor** [comment]
Yes I have, should I close the issue now?
