### ISSUE TITLE
🐛 Bug: Exception eosbase-bentoml-0.11.0-py37 source environment does not exist

### ISSUE THREAD

**Issue by donaldte** [ersilia-os/ersilia#365]
### Describe the bug.

Exception: eosbase-bentoml-0.11.0-py37 source environment does not exist

This bug pops up when I try to fetch any model.
example:
ersilia -v fetch eos4e41 > eos4e41.log

This a log file:
[eos4e41.log](https://github.com/ersilia-os/ersilia/files/9800685/eos4e41.log)

### Describe the steps to reproduce the behavior

1. got to ersilia with : cd ersilia
2. activate ersilia with: conda  activate ersilia
3. fetch a model  with: ersilia -v fetch eos4e41 > eos4e41.log

### Expected behavior.

When I execute this last command which allows us to fetch a model after a few minutes of installing the packages, the terminal displays this:

    $ conda update -n base -c defaults conda

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/python-3.7.13-h12debd9_0.conda>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

Could not find conda environment: eosbase-bentoml-0.11.0-py37
You can list all discoverable environments with `conda info --envs`.

13:23:06 | INFO     | Cloning base conda environment and adding model dependencies
Traceback (most recent call last):
  File "/home/ing/anaconda3/envs/ersilia/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/ing/anaconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/ing/wprojects/ersilia/ersilia/cli/commands/fetch.py", line 33, in fetch
    _fetch(mf, model_id)
  File "/home/ing/wprojects/ersilia/ersilia/cli/commands/fetch.py", line 12, in _fetch
    mf.fetch(model_id)
  File "/home/ing/wprojects/ersilia/ersilia/hub/fetch/fetch.py", line 98, in fetch
    self._pack()
  File "/home/ing/wprojects/ersilia/ersilia/hub/fetch/fetch.py", line 69, in _pack
    mp.pack()
  File "/home/ing/wprojects/ersilia/ersilia/hub/fetch/actions/pack.py", line 63, in pack
    self._run()
  File "/home/ing/wprojects/ersilia/ersilia/hub/fetch/actions/pack.py", line 58, in _run
    runner.run()
  File "/home/ing/wprojects/ersilia/ersilia/hub/fetch/pack/runners.py", line 141, in run
    self._run()
  File "/home/ing/wprojects/ersilia/ersilia/hub/fetch/pack/runners.py", line 123, in _run
    env = self._setup()
  File "/home/ing/wprojects/ersilia/ersilia/hub/fetch/pack/runners.py", line 105, in _setup
    self.conda.clone(base_env, env)
  File "/home/ing/wprojects/ersilia/ersilia/utils/conda.py", line 335, in clone
    raise Exception("{0} source environment does not exist".format(src_env))
Exception: eosbase-bentoml-0.11.0-py37 source environment does not exist

### Screenshots.

ubuntu 22.04 LTS

### Operating environment

Ubuntu 22.04 LTS

**Comment by GemmaTuron** [comment]
Seems like there is a problem with your conda installation, can you run `conda env list` and paste the output here? (it will show all the envs available to you)

**Comment by donaldte** [comment]
@GemmaTuron  After run conda env list 
This is the output
![Screenshot from 2022-10-17 14-30-22](https://user-images.githubusercontent.com/81464575/196190631-7e55bb49-d6eb-4377-b1ef-ea6491390795.png)

**Comment by GemmaTuron** [comment]
Thanks, you see how you don't have the eosbase environment listed there?
This should have been created during ersilia's installation... 
- Update pip
- Delete ersilia's conda environment and create it again (make sure its python=3.7)
- Pull latest changes to ersilia's git repository
- and pip install ersilia again

**Comment by GemmaTuron** [comment]
Hello @donaldte 

Have you been able to make progress?

Thanks!

**Comment by GemmaTuron** [comment]
I'll close this issue due to inactivity
