### ISSUE TITLE
🦠 Model Request: Prediction of Aqueous Kinetic Solubility

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#589]
### Model Name

Aqueous Kinetic Solubility

### Model Description

Prediction of Aqueous solubility is one of the most important properties in drug discovery, as it has profound impact on various drug properties, including biological activity, pharmacokinetics (PK), toxicity, and in vivo efficacy.

### Slug

aqueous-kinetic-solubility

### Tag

solubility, ADME

### Publication

https://pubmed.ncbi.nlm.nih.gov/31176566/

### Source Code

 https://github.com/ncats/ncats-adme

### License

None

**Comment by GemmaTuron** [comment]
Hi @pauline-banye can you update me? We are moving the solubility model to this new repo finally to bypass the git-lfs installs?
Let me know when the old repo is ready for deleting to avoid duplications!

**Comment by pauline-banye** [comment]
Hi @GemmaTuron You can delete the old repo. I have all the codes and I have forked and transferred the codes to the newly cloned repo. 

However, I seem to be having an issue with FPSim2 but I believe it is due to my conda environment. When I encountered this issue, I tested the model with a virtual environment on a different terminal (gitbash) and it worked flawlessly. 

I am currently trying to resolve the issues with the FPSim2 dependency on my conda environment.

**Comment by GemmaTuron** [comment]
@pauline-banye following our discussion:

- FPSim2 is only developed for PY3.8 or above, so the conda env should be 3.8
- The output of the model (stable/unstable) is confusing with the solubility / insoluble expected output. Can you clarify if we are using the right model, and if so, what does stable/unstable stand for?

**Comment by pauline-banye** [comment]
My apologies @GemmaTuron , it is supposed to be high solubility and low solubility. I was remiss in editing that string in the repo but I have corrected it.

**Comment by pauline-banye** [comment]
Thank you @GemmaTuron. I deleted the previous repo and all conda environments. The new fork and environment has been upgraded to python 3.8

**Comment by GemmaTuron** [comment]
Perfect, thanks @pauline-banye ! Let me know how it goes with the changes!

**Comment by pauline-banye** [comment]
Hi @GemmaTuron I'm still getting issues with the checks but after time spent debugging, I believe it could be an issue with the python path because the dependencies are installed, it's still returning that module not found error.

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 
Let's try to debug this today, I was able to run it successfully in my system - can you get ready

- List of dependencies you are installing - either manually or through .yml
- List of dependencies you see in your conda env (with versions)
- Python path of the conda environment

**Comment by pauline-banye** [comment]
> Hi @pauline-banye Let's try to debug this today, I was able to run it successfully in my system - can you get ready
> 
> * List of dependencies you are installing - either manually or through .yml
> * List of dependencies you see in your conda env (with versions)
> * Python path of the conda environment

Hi @GemmaTuron, Thank you so much! I would really appreciate it 🙏. I Have pushed the current dependencies to the forked repository but I need to export the dependencies from the current environment.

**Comment by pauline-banye** [comment]
Hi @GemmaTuron ;

As requested, I returned the exact values from the solubility model. Theseb tests were carried out using two different lists of smiles.
- [x] Full output without the _**round**_ command
[eml_sol_full.csv](https://github.com/ersilia-os/ersilia/files/10731834/eml_sol_full.csv)
[input_sol_full.csv](https://github.com/ersilia-os/ersilia/files/10731841/input_sol_full.csv)

- [x] I repeated the model test within the Ersilia CLI using the repo_path command.
[eos74bo_list_run.csv](https://github.com/ersilia-os/ersilia/files/10731107/eos74bo_list_run.csv)
[eos74bo_run.csv](https://github.com/ersilia-os/ersilia/files/10731110/eos74bo_run.csv)

- [x] I also compared the output recieved from NCAT with the output returned by the eos74bo solubility model rounded to two decimal places.
- output from NCAT
[eml_sol_ADME_Predictions_2023-02-14-115722.csv](https://github.com/ersilia-os/ersilia/files/10731738/eml_sol_ADME_Predictions_2023-02-14-115722.csv)
[input.sol_ADME_Predictions_2023-02-14-121509.csv](https://github.com/ersilia-os/ersilia/files/10731775/input.sol_ADME_Predictions_2023-02-14-121509.csv)

- [x] Output from eos74bo (with the results rounded to two decimal places)
- output_df from input.csv
```
Solubility: 0.08900904655456543 seconds to predict 11 molecules
                                               smiles Predicted Class (Probability)       Prediction
0                          CC(=O)Nc1nnc(S(N)(=O)=O)s1                       0 (1.0)  high solubility
1                                         CCCOCCCCCCC                       1 (1.0)   low solubility
2                                           CCCCOCCCC                      1 (0.74)   low solubility
3                             CC(=O)N[C@@H](CS)C(=O)O                       0 (1.0)  high solubility
4                               CC(=O)Oc1ccccc1C(=O)O                      0 (0.98)  high solubility
5                                             CC(=O)O                      1 (0.79)   low solubility
6                              O=c1ncnc2[nH][nH]cc1-2                      1 (0.95)   low solubility
7                                          CCCCNCCCCC                       0 (1.0)  high solubility
8       Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1                       0 (1.0)  high solubility
9                      CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1                      1 (0.99)   low solubility
10  C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...                      0 (0.86)  high solubility
[0.0, 1.0, 0.74, 0.0, 0.020000000000000018, 0.79, 0.95, 0.0, 0.0, 0.99, 0.14]
```
[input_sol.csv](https://github.com/ersilia-os/ersilia/files/10731764/input_sol.csv)

- output_df from eml.csv
```
Solubility: 0.5354588031768799 seconds to predict 10 molecules
                                              smiles Predicted Class (Probability)       Prediction
0      Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1                       0 (1.0)  high solubility
1                         CC(=O)Nc1nnc(S(N)(=O)=O)s1                       0 (1.0)  high solubility
2                                            CC(=O)O                      1 (0.79)   low solubility
3                            CC(=O)N[C@@H](CS)C(=O)O                       0 (1.0)  high solubility
4                              CC(=O)Oc1ccccc1C(=O)O                      0 (0.98)  high solubility
5                       Nc1nc(=O)c2ncn(COCCO)c2[nH]1                       0 (1.0)  high solubility
6  O=C(O[C@H]1C[N+]2(CCCOc3ccccc3)CCC1CC2)C(O)(c1...                      0 (0.99)  high solubility
7  CN(C)C/C=C/C(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2...                      0 (0.74)  high solubility
8                     CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1                      1 (0.99)   low solubility
9                             O=c1ncnc2[nH][nH]cc1-2                      1 (0.95)   low solubility
[0.0, 0.0, 0.79, 0.0, 0.020000000000000018, 0.0, 0.010000000000000009, 0.26, 0.99, 0.95]
```
[eml_sol.csv](https://github.com/ersilia-os/ersilia/files/10731741/eml_sol.csv)

**Comment by GemmaTuron** [comment]
Hi @pauline-banye! 
Thanks for this. I am a bit confused because each file has different names, so I don't know which result corresponds to what. I want to make sure that we are always returning the **probability of 1**
Can you let me know what do you get when predicting the following molecules: `CC(=O)Oc1ccccc1C(=O)O` and `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1` with the Ersilia Repo and with the Original code?

Thanks!

**Comment by GemmaTuron** [comment]
Looking a bit more into the results, now I understand we are giving as output the latest line I see on the code, for example: [0.0, 0.0, 0.79, 0.0, 0.020000000000000018, 0.0, 0.010000000000000009, 0.26, 0.99, 0.95] in the last one right?

so that should be fine

**Comment by GemmaTuron** [comment]
Two comments just to close this:
Can we name the column: "proba1" instead of "value" in the Ersilia Model Hub output?
And could the output have a SMILES column + Proba1 column? for easier interpretation of the results

**Comment by pauline-banye** [comment]
> Two comments just to close this: Can we name the column: "proba1" instead of "value" in the Ersilia Model Hub output? And could the output have a SMILES column + Proba1 column? for easier interpretation of the results

Hi @GemmaTuron,
I have adjusted the code and this is the current output being returned. I have renamed the columns and included the smiles and proba1 columns in the return. I am currently testing the codes in the Ersilia CLI.
[out.csv](https://github.com/ersilia-os/ersilia/files/10741029/out.csv)

**Comment by pauline-banye** [comment]
> `CC(=O)Oc1ccccc1C(=O)O` and `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1`

@GemmaTuron I'm so sorry I made it confusing, I was a bit overzealous and tried to account for all the possible test cases. Let me attempt to clarify.
- I ran the tests with two different lists of smiles.
- I repeated the tests with the original NCAT codes and within Ersilia.
- I also ran them with the exact output values and rounded to 2 decimal places.

**Comment by pauline-banye** [comment]
> Hi @pauline-banye! Thanks for this. I am a bit confused because each file has different names, so I don't know which result corresponds to what. I want to make sure that we are always returning the **probability of 1** Can you let me know what do you get when predicting the following molecules: `CC(=O)Oc1ccccc1C(=O)O` and `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1` with the Ersilia Repo and with the Original code?
> 
> Thanks!


@GemmaTuron I'm so sorry I made it confusing, I was a bit overzealous and tried to account for all the possible test cases. Let me attempt to clarify.
- I ran the tests with two different lists of smiles.
- I repeated the tests with the original NCAT codes and within Ersilia.
- I also ran them with the exact output values and rounded to 2 decimal places.

**Comment by pauline-banye** [comment]
> Hi @pauline-banye! Thanks for this. I am a bit confused because each file has different names, so I don't know which result corresponds to what. I want to make sure that we are always returning the **probability of 1** Can you let me know what do you get when predicting the following molecules: `CC(=O)Oc1ccccc1C(=O)O` and `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1` with the Ersilia Repo and with the Original code?
> 
> Thanks!

@GemmaTuron I'm so sorry I made it confusing, I was a bit overzealous and tried to account for all the possible test cases. Let me attempt to clarify.
- I ran the tests with two different lists of smiles.
- I repeated the tests with the original NCAT codes and within Ersilia.
- I also ran them with the exact output values and rounded to 2 decimal places.

I have tested the new output with the smiles you requested
[output_smiles.csv](https://github.com/ersilia-os/ersilia/files/10743033/output_smiles.csv)

I however encountered an error `TypeError: 'NoneType' object is not subscriptable` whilst running the code within Ersilia.
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/ersilia/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/root/miniconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/pauline/ersilia/ersilia/cli/commands/api.py", line 37, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/pauline/ersilia/ersilia/core/model.py", line 343, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/pauline/ersilia/ersilia/core/model.py", line 357, in api_task
    for r in result:
  File "/home/pauline/ersilia/ersilia/core/model.py", line 184, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/home/pauline/ersilia/ersilia/serve/api.py", line 330, in post
    results, output, model_id=self.model_id, api_name=self.api_name
  File "/home/pauline/ersilia/ersilia/io/output.py", line 283, in adapt
    df = self._to_dataframe(result)
  File "/home/pauline/ersilia/ersilia/io/output.py", line 229, in _to_dataframe
    output_keys_expanded = self.__expand_output_keys(vals, output_keys)
  File "/home/pauline/ersilia/ersilia/io/output.py", line 197, in __expand_output_keys
    t = self._guess_pure_dtype_if_absent(v)
  File "/home/pauline/ersilia/ersilia/io/output.py", line 181, in _guess_pure_dtype_if_absent
    return dtype["type"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pauline-banye** [comment]
> Two comments just to close this: Can we name the column: "proba1" instead of "value" in the Ersilia Model Hub output? And could the output have a SMILES column + Proba1 column? for easier interpretation of the results

@GemmaTuron 
Ersilia actually already accounts for the smile name in the output returned. I did try it out as you suggested but it returned errors which would require possibly editing the Ersilia codebase. Below is the error that I encountered when I tried adding the smile name as part of the result.
```
File "/home/pauline/ersilia/ersilia/cli/commands/api.py", line 37, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/pauline/ersilia/ersilia/core/model.py", line 343, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/pauline/ersilia/ersilia/core/model.py", line 357, in api_task
    for r in result:
  File "/home/pauline/ersilia/ersilia/core/model.py", line 184, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/home/pauline/ersilia/ersilia/serve/api.py", line 330, in post
    results, output, model_id=self.model_id, api_name=self.api_name
  File "/home/pauline/ersilia/ersilia/io/output.py", line 283, in adapt
    df = self._to_dataframe(result)
  File "/home/pauline/ersilia/ersilia/io/output.py", line 229, in _to_dataframe
    output_keys_expanded = self.__expand_output_keys(vals, output_keys)
  File "/home/pauline/ersilia/ersilia/io/output.py", line 197, in __expand_output_keys
    t = self._guess_pure_dtype_if_absent(v)
  File "/home/pauline/ersilia/ersilia/io/output.py", line 181, in _guess_pure_dtype_if_absent
    return dtype["type"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by GemmaTuron** [comment]
Thanks for testing! @miquelduranfrigola qhat do you think? should we just give the number as output?

**Comment by GemmaTuron** [comment]
This model is completed.
