### ISSUE TITLE
🐛 Bug: `ersilia catalog --mode <mode>` erroring with AttributeError

### ISSUE THREAD

**Issue by Lehcar** [ersilia-os/ersilia#697]
### Describe the bug.

I'm seeing `AttributeError: 'NoneType' object has no attribute 'lower'` when I run `ersilia catalog --mode "Retrained"`.

Full logs with stacktrace:
```
(base) lehcar@rachels-mbp ersilia % ersilia catalog --mode "Retrained"
Traceback (most recent call last):
  File "/Users/lehcar/anaconda3/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/Users/lehcar/workspace/ersilia/ersilia/cli/commands/catalog.py", line 65, in catalog
    catalog = ModelSearcher(catalog).search_mode(mode)
  File "/Users/lehcar/workspace/ersilia/ersilia/hub/content/search.py", line 89, in search_mode
    r_ = r[3].lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

I've also tried the following commands:
- `ersilia catalog --mode trained`
- `ersilia catalog --mode "trained"`
- `ersilia catalog --mode 'trained'`
- `ersilia catalog --mode Retrained`

Running this in verbose mode (running `ersilia -v catalog --mode "Retrained"`) gave me the following error:

<details>
  <summary>Verbose mode output</summary>

  ```
(base) lehcar@rachels-mbp ersilia % ersilia -v catalog --mode "Retrained"
00:09:11 | DEBUG    | Looking for model repositories in ersilia-os organization
00:09:12 | INFO     | Found 9 models
00:09:12 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos1086
00:09:13 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos1579
00:09:14 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos157v
00:09:14 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos1af5
00:09:15 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos1amn
00:09:16 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos1amr
00:09:16 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos1bba
00:09:17 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos1vms
00:09:18 | DEBUG    | Trying to get metadata from: /Users/lehcar/eos/dest/eos22io
Traceback (most recent call last):
  File "/Users/lehcar/anaconda3/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/Users/lehcar/anaconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/Users/lehcar/workspace/ersilia/ersilia/cli/commands/catalog.py", line 65, in catalog
    catalog = ModelSearcher(catalog).search_mode(mode)
  File "/Users/lehcar/workspace/ersilia/ersilia/hub/content/search.py", line 89, in search_mode
    r_ = r[3].lower()
AttributeError: 'NoneType' object has no attribute 'lower'
  ```
</details>

### Describe the steps to reproduce the behavior

1. Run `ersilia catalog --mode Retrained`

### Expected behavior.

I would expect to see information on the following models: `[eos1086, eos1579, eos157v eos1af5, eos1amn, eos1amr, eos1bba, eos1vms, eos22io]`

### Operating environment

macOS Monterey 12.6.6 (Intel)

### Additional context

I wasn't running ersilia in a conda environment and I don't have any local models.

**Comment by Lehcar** [comment]
This could also be me misunderstanding the function of this search. I see `Trying to get metadata from: /Users/lehcar/eos/dest/eos1086` in the verbose output which leads me to believe ersilia may be trying to pull this metadata locally.

**Comment by miquelduranfrigola** [comment]
Hello @Lehcar - thanks so much for raising this issue.

I have cleaned the `catalog` command, since it had a lot of legacy arguments (such as `--mode`) that we did not test appropriately.

I have removed search capabilities for now, and also pagination.

This should work now:

```bash
ersilia catalog -f my_catalog.csv
```

This will simply give you a file with a list of all available model ids in the Ersilia Model Hub. For now, for a more interactive search of the repository, we recommend checking the AirTable. You can open it in your browser:

```bash
ersilia catalob --browser
```
