### ISSUE TITLE
🐛 Bug: "REINVENT 4 Mol2MolMediumSimilarity" integration fails due to Python version mismatch in base Docker image. 

### ISSUE THREAD

**Issue by ankitskvmdam** [ersilia-os/ersilia#970]
### Describe the bug.

REINVENT 4 Mol2MolMediumSimilarity ([eos694w](https://github.com/ankitskvmdam/eos694w)) integration is blocked due to a Python version mismatch in the base Docker image. 

`reinvent` requires Python >=3.10 (https://github.com/MolecularAI/REINVENT4?tab=readme-ov-file#requirements), while the current image only offers 3.7 (bentoml/model-server:0.11.0-py37). 

### Operating environment

Windows 11

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam - @DhanshreeA do you have any ideas about how to solve this?

**Comment by ankitskvmdam** [comment]
@DhanshreeA Got it!

However it makes it harder to test locally. As I need to do multiple steps. Is there a way to replicate what Ersilia is doing under the hood?

**Comment by DhanshreeA** [comment]
Hey @ankitskvmdam I agree, it is a bit inconvenient indeed. You cannot test the Docker build as it is, but you can test the model end-to-end locally using the `repo_path` flag within ersilia `fetch` command. 

So as a general practice, for local testing, I would recommend you test the model in a compatible conda environment outside of a model repository. Once you are convinced it works, add the required dependencies and Python version within the Dockerfile. After that, you can test it locally like so: `ersilia -v fetch eosxxx --repo_path /path/to/eosxxxx`. Hope this helps!

**Comment by miquelduranfrigola** [comment]
Thanks @DhanshreeA
Quite clearly, when we re-define the template we need to rethink the `Dockerfile`. Thanks @ankitskvmdam for the feedback.

**Comment by DhanshreeA** [comment]
@ankitskvmdam Let us know if it works, and we'll close the issue! :)

**Comment by ankitskvmdam** [comment]
@DhanshreeA I will try this over the weekend and the let you know.

**Comment by ankitskvmdam** [comment]
@DhanshreeA Yes, it works. Thanks!

**Comment by DhanshreeA** [comment]
Awesome, thanks for updating @ankitskvmdam. I am closing this issue now.

**Comment by miquelduranfrigola** [comment]
Awesome - let me try it.

**Comment by ankitskvmdam** [comment]
@DhanshreeA I am getting the following error when I am running `ersilia -v fetch eosxxx --repo_path /path/to/eosxxxx` :

```
Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos694w:run did not produce an outputTraceback (most recent call last):
  File "/root/eos/repository/eos694w/20240305123400_34C3A8/eos694w/artifacts/framework/code/main.py", line 10, in <module>
    from mol2mol_similarity_sampler import Mol2MolSimilaritySampler
  File "/root/eos/repository/eos694w/20240305123400_34C3A8/eos694w/artifacts/framework/code/mol2mol_similarity_sampler.py", line 6, in <module>
    from reinvent.runmodes import samplers, create_adapter
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/reinvent/runmodes/__init__.py", line 5, in <module>
    from reinvent.runmodes.samplers.run_sampling import run_sampling
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/reinvent/runmodes/samplers/__init__.py", line 5, in <module>
    from .libinvent import *
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/reinvent/runmodes/samplers/libinvent.py", line 14, in <module>
    from reinvent.runmodes.utils.helpers import join_fragments
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/reinvent/runmodes/utils/__init__.py", line 6, in <module>
    from .image import *
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/reinvent/runmodes/utils/image.py", line 14, in <module>
    from reinvent.chemistry.logging import (
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/reinvent/chemistry/logging.py", line 9, in <module>
    from torch.utils.tensorboard import summary as tbs
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/tensorboard/compat/proto/event_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/tensorboard/compat/proto/summary_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import histogram_pb2 as tensorboard_dot_compat_dot_proto_dot_histogram__pb2
  File "/root/miniconda3/envs/eos694w/lib/python3.10/site-packages/tensorboard/compat/proto/histogram_pb2.py", line 21, in <module>
    _HISTOGRAMPROTO = DESCRIPTOR.message_types_by_name['HistogramProto']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

#### Step to reproduce

1. Go to https://github.com/ersilia-os/ersilia and create a codespace.
2. In the codespace's terminal run `git clone https://github.com/ankitskvmdam/eos694w`
3. Run `ersilia -v fetch eos694w --repo_path ./eos694w`


It seems to be related to the TensorBoard and ProtoBuf libraries.
